# Generated by Django 3.1.1 on 2020-09-29 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.user')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('date_of_birth', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('military_classification', models.CharField(blank=True, max_length=100, null=True)),
                ('military_branch', models.CharField(blank=True, max_length=100, null=True)),
                ('military_rank', models.CharField(blank=True, max_length=100, null=True)),
                ('military_completed', models.CharField(blank=True, max_length=100, null=True)),
                ('military_completed_reason', models.CharField(blank=True, max_length=100, null=True)),
                ('military_term', models.CharField(blank=True, max_length=100, null=True)),
                ('highschool_name', models.CharField(blank=True, max_length=100, null=True)),
                ('highschool_classification', models.CharField(blank=True, max_length=100, null=True)),
                ('highschool_location', models.CharField(blank=True, max_length=100, null=True)),
                ('highschool_entrance_year', models.CharField(blank=True, max_length=100, null=True)),
                ('highschool_graduation_year', models.CharField(blank=True, max_length=100, null=True)),
                ('college_name', models.CharField(blank=True, max_length=100, null=True)),
                ('college_classification', models.CharField(blank=True, max_length=100, null=True)),
                ('college_location', models.CharField(blank=True, max_length=100, null=True)),
                ('college_entrance_year', models.CharField(blank=True, max_length=100, null=True)),
                ('college_graduation_year', models.CharField(blank=True, max_length=100, null=True)),
                ('college_major', models.CharField(blank=True, max_length=100, null=True)),
                ('college_minor', models.CharField(blank=True, max_length=100, null=True)),
                ('college_grade', models.FloatField(blank=True, null=True)),
                ('university_name', models.CharField(blank=True, max_length=100, null=True)),
                ('university_classification', models.CharField(blank=True, max_length=100, null=True)),
                ('university_location', models.CharField(blank=True, max_length=100, null=True)),
                ('university_entrance_year', models.CharField(blank=True, max_length=100, null=True)),
                ('university_graduation_year', models.CharField(blank=True, max_length=100, null=True)),
                ('university_major', models.CharField(blank=True, max_length=100, null=True)),
                ('university_minor', models.CharField(blank=True, max_length=100, null=True)),
                ('university_grade', models.FloatField(blank=True, null=True)),
                ('master_name', models.CharField(blank=True, max_length=100, null=True)),
                ('master_classification', models.CharField(blank=True, max_length=100, null=True)),
                ('master_location', models.CharField(blank=True, max_length=100, null=True)),
                ('master_entrance_year', models.CharField(blank=True, max_length=100, null=True)),
                ('master_graduation_year', models.CharField(blank=True, max_length=100, null=True)),
                ('master_major', models.CharField(blank=True, max_length=100, null=True)),
                ('master_minor', models.CharField(blank=True, max_length=100, null=True)),
                ('master_grade', models.FloatField(blank=True, null=True)),
                ('doctor_name', models.CharField(blank=True, max_length=100, null=True)),
                ('doctor_classification', models.CharField(blank=True, max_length=100, null=True)),
                ('doctor_location', models.CharField(blank=True, max_length=100, null=True)),
                ('doctor_entrance_year', models.CharField(blank=True, max_length=100, null=True)),
                ('doctor_graduation_year', models.CharField(blank=True, max_length=100, null=True)),
                ('doctor_major', models.CharField(blank=True, max_length=100, null=True)),
                ('doctor_minor', models.CharField(blank=True, max_length=100, null=True)),
                ('doctor_grade', models.FloatField(blank=True, null=True)),
                ('veterans_classification', models.CharField(blank=True, max_length=100, null=True)),
                ('veterans_number', models.CharField(blank=True, max_length=100, null=True)),
                ('obstacle_classification', models.CharField(blank=True, max_length=100, null=True)),
                ('obstacle_grade', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('score', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.CharField(blank=True, max_length=100, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.article')),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('publisher', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.CharField(blank=True, max_length=100, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.article')),
            ],
        ),
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('term', models.CharField(blank=True, max_length=100, null=True)),
                ('retirement_reason', models.CharField(blank=True, max_length=100, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('rank', models.CharField(blank=True, max_length=100, null=True)),
                ('duty', models.CharField(blank=True, max_length=100, null=True)),
                ('statement', models.TextField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.article')),
            ],
        ),
    ]
