<<<<<<< HEAD:backend-django/backend/articles/migrations/0002_auto_20201005_1815.py
# Generated by Django 3.1.1 on 2020-10-05 09:15
=======
# Generated by Django 3.1.1 on 2020-10-05 08:38
>>>>>>> 2285440e1eb0abdc4932bcdab4397b6fe24b4d2b:backend-django/backend/articles/migrations/0002_auto_20201005_1738.py

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD:backend-django/backend/articles/migrations/0002_auto_20201005_1815.py
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recruitments', '0001_initial'),
        ('articles', '0001_initial'),
=======
        ('recruitments', '0001_initial'),
        ('articles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
>>>>>>> 2285440e1eb0abdc4932bcdab4397b6fe24b4d2b:backend-django/backend/articles/migrations/0002_auto_20201005_1738.py
    ]

    operations = [
        migrations.AddField(
            model_name='selfintroduction',
            name='recruitment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruitments.recruitment'),
        ),
        migrations.AddField(
            model_name='selfintroduction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='language',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.article'),
        ),
        migrations.AddField(
            model_name='language',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='certificate',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.article'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='career',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.article'),
        ),
        migrations.AddField(
            model_name='career',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='article',
            name='buyer',
            field=models.ManyToManyField(blank=True, related_name='seller', to=settings.AUTH_USER_MODEL),
        ),
    ]
