# Generated by Django 3.1.1 on 2020-09-29 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='military_term',
            new_name='military_end',
        ),
        migrations.RenameField(
            model_name='career',
            old_name='term',
            new_name='end_term',
        ),
        migrations.AddField(
            model_name='article',
            name='college_total',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='doctor_total',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='master_total',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='military_start',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='university_total',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='career',
            name='start_term',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
